### ISSUE TITLE
Will not compile with current version of Mini-XML

### ISSUE THREAD

**Issue by eschuler21** [tjko/nxgipd#12]
I read through all the other issues and comments, and got it to compile with Mini-XML ver 2.9.  With the current version of Mini-XML (2.12), I was getting the following error:

gcc  -Wall -g -O2  -DHAVE_CONFIG_H -DVERSION=\"1.1.1beta\" -DBUILDDATE=\"2019-01-12\"   -c -o configuration.o configuration.c
configuration.c: In function ‘search_xml_tree’:
configuration.c:70:11: error: dereferencing pointer to incomplete type ‘mxml_node_t {aka struct _mxml_node_s}’
   if (node->type != type) {
           ^~
configuration.c: In function ‘xml_whitespace_cb’:
configuration.c:85:39: warning: ‘~’ on a boolean expression [-Wbool-operation]
   } else if ( !strcmp(name,"Zone") || ~!strcmp(name,"Partition") ) {
                                       ^
configuration.c:85:39: note: did you mean to use logical not?
   } else if ( !strcmp(name,"Zone") || ~!strcmp(name,"Partition") ) {
                                       ^
                                       !
<builtin>: recipe for target 'configuration.o' failed
make: *** [configuration.o] Error 1

**Comment by juanjoSanz** [comment]
Have you managed to solve this issue?

I tried to compile on an arm system with ubuntu linux, but I found two issues:

1) config/config.guess file does not recognize my system.
Workaround: replace config/config.guess with /usr/share/automake-1.xx/config.guess

2) you're same error. How did you solve it?

```user@hostname:~/nx/nxgipd$ make
gcc  -Wall -g -O2  -DHAVE_CONFIG_H -DVERSION=\"1.1.1beta\" -DBUILDDATE=\"2021-11-04\"   -c -o configuration.o configuration.c
configuration.c: In function ‘search_xml_tree’:
configuration.c:70:11: error: dereferencing pointer to incomplete type ‘mxml_node_t’ {aka ‘struct _mxml_node_s’}
   70 |   if (node->type != type) {
      |           ^~
configuration.c: In function ‘xml_whitespace_cb’:
configuration.c:85:39: warning: ‘~’ on a boolean expression [-Wbool-operation]
   85 |   } else if ( !strcmp(name,"Zone") || ~!strcmp(name,"Partition") ) {
      |                                       ^
configuration.c:85:39: note: did you mean to use logical not?
   85 |   } else if ( !strcmp(name,"Zone") || ~!strcmp(name,"Partition") ) {
      |                                       ^
      |                                       !
make: *** [<builtin>: configuration.o] Error 1
```

**Comment by tjko** [comment]
There is now fix for Mini-XML v3.x checked in: 5123887c520010ee9716d7ffc06a88e071447c80

It would be great if someone could validate that it works ok, since I can't immediately test this change.
